### ISSUE TITLE
overflow error

### ISSUE THREAD

**Issue by piplus2** [sandberg-lab/txburst#14]
Hi!
I'm getting this error

`\anaconda3\envs\txburst\lib\site-packages\scipy\special\orthogonal.py:265: RuntimeWarning: overflow encountered in double_scalars`
`mu0 = 2.0**(alpha+beta+1)*cephes.beta(alpha+1, beta+1)`
`txburstML.py:43: RuntimeWarning: invalid value encountered in multiply`
`prob = 1/beta_fun(alpha, bet)*2**(-alpha-bet+1)*gs`

Could you please help with that?

**Comment by AntonJMLarsson** [comment]
Hello,
You don't need to worry about this warning. It can be safely ignored. Most likely it occurred due for a gene with very low expression which would anyway not be informative.

Best,
Anton
