### ISSUE TITLE
NA p-values from txburstTEST.py

### ISSUE THREAD

**Issue by piplus2** [sandberg-lab/txburst#16]
Hi, I'm doing a differential analysis of burst frequency between two cell populations.
Several genes have an NA p-value, is there a specific reason why this is happening?

Thank you!

**Comment by AntonJMLarsson** [comment]
Hello,

This occurs if the algorithm failed in the optimization step to find the most likely fold change. This usually happens if one of the conditions has very few detected molecules across all cells. 

Best,
Anton

**Comment by piplus2** [comment]
I see. Thank you for the details!
