### ISSUE TITLE
Error while running txburstML.py

### ISSUE THREAD

**Issue by srishastry123** [sandberg-lab/txburst#17]
Hello great work 

I wanted analyze my data using txburst when I am running your one the data file(SS3_cast_UMIs_mESC.csv) I am getting error as below its warning can I ignore it or is there any significance 

/home/.local/lib/python3.6/site-packages/scipy/special/orthogonal.py:1347: RuntimeWarning: invalid value encountered in double_scalars
  mu0 = np.sqrt(np.pi) * cephes.gamma(alpha + 0.5) / cephes.gamma(alpha + 1)
./txburstML.py:43: RuntimeWarning: divide by zero encountered in double_scalars
  prob = 1/beta_fun(alpha, bet)*2**(-alpha-bet+1)*gs

I am getting the output but  getting different output values  which is almost similar but not exactly same

command what I have run 
`./txburstML.py data/SS3_cast_UMIs_mESC.csv`

output what  I got
[files](https://github.com/srishastry123/new.git)

Please  help me your input will be very helpful

Thank you

**Comment by AntonJMLarsson** [comment]
Hello,

Don't worry if it's not identical. The maximum likelihood method uses a numerical method to calculate the likelihoods, so those might differ slightly depending on which machine you run it on.

You also don't have to worry about the runtime warning. This happens occasionally for very lowly expressed genes.

Best,
Anton
