### ISSUE TITLE
Parameters (burst freq and burst size) outside fig 1b range

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [sandberg-lab/txburst#7]
I was re-doing the steps to create figure 1b with the data you provide (`SS3_cast_UMIs_concat_ML.pkl`), however I noticed something strange when plotting these values:
![whatshappening](https://user-images.githubusercontent.com/15323399/65495015-45531e00-deb6-11e9-831e-acaae3dc5e55.gif)

Many (most?) of the values are outside of the burst-size and burst-frequency range you show in the plot. When I plot the `SS3_cast_UMIs_concat_PL.pkl` pickle file the values only exist within the range of the figure. 

I am a bit confused as to why these values are clipped. I couldn't find how this decision boundary was chosen in the paper. Why do we allow burst sizes below 1 during the fitting process, but then filter those values out afterwards? Why don't we make use of the contour in the background (inference precision)?

I have difficulty interpreting this contour. In my understanding: the higher a value, the less sensitive the likelihood is to the parameters, and vice versa. But how do I interpret this? When the value is low, does it then mean the model is (probably) overfitting because of the sensitivity? When the value is high, does it mean that the inferred parameters might be very far off, since a wide range of parameters can generate the same dynamics?

**Comment by AntonJMLarsson** [comment]
Hi! Regarding the contour, lower is better. The information contained within observations depends on where in the parameter space those observations were generated. I would not call it overfitting, just that one would require fewer observations to obtain a good estimate. 

For the maximum likelihood estimation I include bounds for the parameters. Most of the clipped values are on the edge of these boundaries and I also found that genes with an inferred burst size lower than one are usually quite inaccurate (for genes with very low burst size we would need more observations). So that is the reason why those genes are excluded.

**Comment by Maarten-vd-Sande** [comment]
Thanks for the fast reply. 

About the contour: Sure. However I am still unsure about why we would use this type of method. Why not generate data, and see how well we can infer the parameters, and plot the difference in inferred parameters and 'true' parameters? Isn't that what we are interested in?

ML estimation: Makes sense. Could we e.g. use the contour for a more "consistent" cutoff?

**Comment by Maarten-vd-Sande** [comment]
And am I correct in my understanding that the contour only shows the sensitivity for the burst size, and not burst frequency?

![image](https://user-images.githubusercontent.com/15323399/65513642-e7d1c800-dedb-11e9-874e-5731526d7e7b.png)

**Comment by Maarten-vd-Sande** [comment]
I mean something like this in my earlier comment:
![image](https://user-images.githubusercontent.com/15323399/65519568-69c6ee80-dee6-11e9-83ad-4baa443e8d6b.png)

This is the normalized euclidian distance between the true parameters and the correspondig fit (n=25) on a log10 scale:
`np.linalg.norm((estimation - np.array([lambd, mu, nu])) / np.array([lambd, mu, nu])) `

It follows a very similar pattern to the original figure, however the values are easier to interpret, much faster to compute, and easier to program.  

Note that there is only a really small space in the center where the parameters are close to their real values, <10^-0.5

**Comment by Maarten-vd-Sande** [comment]
Here is the same one (on a lower resolution) with a 1000 cells when estimating parameters (opposed to 100 in the previous image):
![image](https://user-images.githubusercontent.com/15323399/65522353-ecea4380-deea-11e9-9692-73b59093c60f.png)

Note that the scales on both images are NOT the same. More cells does lead to a very significantly better estimation!

**Comment by AntonJMLarsson** [comment]
Yes, I agree that it would also address the question of how accuracy of the inference. 

One reason to show involve the confidence intervals is to also give some information about how well the profile likelihood method performs, which we also use for differential burst kinetics hypothesis testing.

You're right that the contour plot in the main figure is for burst frequency, the burst size one is similar.

**Comment by Maarten-vd-Sande** [comment]
Thanks for the answers, it has been very helpful in understanding :smile: !
