### ISSUE TITLE
Profile likelihood calculation

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [sandberg-lab/txburst#8]
I am a bit confused as to how the p-values are calculated for hypothesis testing. When studying the calculation of the profile likelihood it looks like you are doing the [Wald test](https://en.wikipedia.org/wiki/Wald_test). Could you explain why/how you estimate the likelihood from:

The Wald statistic takes this form:

> (theta_H - theta_A)^2 / var(theta_H)

And you calculate it like:

> 2 * (theta_H - theta_A)

I can't seem to figure out how we go from the one to the other.

**Comment by Maarten-vd-Sande** [comment]
Oh and is there a reason why TNC is used instead of L-BFGS-B?

**Comment by AntonJMLarsson** [comment]
The test used is the likelihood-ratio test https://en.wikipedia.org/wiki/Likelihood-ratio_test

In this case there are no bounds needed so I use TNC. But both would work well.

**Comment by Maarten-vd-Sande** [comment]
Cool, thanks for answering all my questions :smile: !!
