### ISSUE TITLE
MaximumLikelihood estimation depends on order of input values

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [sandberg-lab/txburst#9]
The order of input has a strong influence on the estimated values
```
vals = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 3])
for i in range(3):
    np.random.shuffle(vals)
    print(MaximumLikelihood(vals))

>>> [1.0070674  1.21945588 1.82469394]
>>> [0.43839056 0.28185839 1.343145  ]
>>> [1.8370356  2.37280682 1.87865225]
```
What is going on here? These difference shouldn't be that big right?

**Comment by Maarten-vd-Sande** [comment]
If I set the tolerance in the minimize function to e.g. 0.99 I do get constant output. However I have no idea what this value means :angel: 

**edit**:

https://github.com/scipy/scipy/blob/d56fcfed9bfe05bbfe3716186c6e494921c48c3c/scipy/optimize/_minimize.py#L566

So it sets the ftol value:
> ftol: float
>     The iteration stops when
> ` (f^k - f^{k+1})/max{|f^k|,|f^{k+1}|,1} <= ftol.`

of which the default is: `2.220446049250313e-09`

https://docs.scipy.org/doc/scipy/reference/optimize.minimize-lbfgsb.html#optimize-minimize-lbfgsb

Not exactly sure how to interpret those values, but it seems that it sets the minimum gradient change..? The problem is now with those low values the optimizer gets stuck in different local optima, but with higher values they get stuck in the same (local) optimum. How do we interpret this? Is it better to have a higher tolerance, but we at least have consistent values between samples?

**Comment by AntonJMLarsson** [comment]
Seems like the ML estimation becomes unreliable with so few observations, the numerical accuracy probably suffers quite a bit and the order of summation in the minimization process may play a role. 

With enough samples (enough to infer kinetics reliably anyway) this completely disappears. The tolerance parameter loosely sets how small to gradient jump is to be considered done.

The log-likelihood is theoretically convex so this problem is numerical.

**Comment by Maarten-vd-Sande** [comment]
Thanks for the reply! 

That indeed seems to be the problem. However even with large(r) data I still have this issue when the data for instance consists mainly of zeros. Probably best to filter this type of data before ML estimation? Also these values will have a burst size of below 1, so they didn't make the original cutoff anyways.
```
vals = np.zeros(500)
vals[:3] = 1

for i in range(3):
    np.random.shuffle(vals)
    print(MaximumLikelihood(vals))

>>> [  2.73015383 451.79873368   1.        ]
>>> [ 0.2473564  40.48483667  1.        ]
>>> [  6.0389935  999.99183207   1.        ]
```

**Comment by AntonJMLarsson** [comment]
Yes these gene would be filtered out because of multiple reasons.  Good catch though! I didn't realize that this edge case could occur.
